Updates - Sources
imagina/imaginacms-requestable pull request #23
Opened 2023-11-24 21:46 UTC by willvrd

2023-11-24 21:55 UTC, JCEC007 requested changes

2023-11-24 21:55 UTC, JCEC007 commented on Repositories/Eloquent/EloquentSourceRepository.php
> +    if (!isset($params->permissions['requestable.sources.index-all']) || (isset($params->permissions['requestable.sources.index-all']) &&
en este if puede ahorrarse el 2do isset(permission), ya que si no se cumple el primero entonces ya se sabe que si existe, solo evalúa que sea false

2023-11-24 21:57 UTC, JCEC007 requested changes

2023-11-24 21:57 UTC, JCEC007 commented on Repositories/Eloquent/EloquentRequestableRepository.php
> +          if (!isset($params->permissions['requestable.sources.index-all']) || (isset($params->permissions['requestable.sources.index-all']) &&
Igual aquí, ahorra el 2do isset

2023-11-24 21:57 UTC, JCEC007 commented on Repositories/Eloquent/EloquentRequestableRepository.php
> +            $query->orWhereHas('source', function ($query) use ($user) {
Where Has son muy lentos, este tipo de queries deben hacerse con WhereRaw
siga el ejemplo de este repo
https://github.com/imagina/imaginacms-iblog/blob/cabf52fbd6a8e6b08b79ff8f2270391a5787afb7/Repositories/Eloquent/EloquentPostRepository.php#L56

2023-11-27 13:50 UTC, willvrd commented on Repositories/Eloquent/EloquentSourceRepository.php
> +    if (!isset($params->permissions['requestable.sources.index-all']) || (isset($params->permissions['requestable.sources.index-all']) &&
Listo

2023-11-27 13:51 UTC, willvrd commented on Repositories/Eloquent/EloquentRequestableRepository.php
> +          if (!isset($params->permissions['requestable.sources.index-all']) || (isset($params->permissions['requestable.sources.index-all']) &&
Listo

2023-11-27 21:19 UTC, willvrd commented on Repositories/Eloquent/EloquentRequestableRepository.php
> +            $query->orWhereHas('source', function ($query) use ($user) {
Listo

2023-11-27 21:20 UTC, JCEC007 approved these changes

2023-11-27 21:21 UTC, merged